#!/bin/bash
# -ublast $chitsfaaFile -db $seqFile -evalue $maxEvalue -blast6out $ublastFile >& /dev/null"
# -fastx_findorfs $input -ntout nucleotide_out_filename -aaout aminoacid_out_filename -orfstyle 7 -mincodons 16



echo "RUNNING USEARCH REPLACEMENT"
PATH=../mmseqs/bin/:$PATH
uvar_blast="-ublast"
uvar_fastx="-fastx_findorfs"
if [ "$1" == "$uvar_blast" ]; 
then
    echo "GOING TO RUN PYTHON"
    python3 ../bin/main.py -ublast $2 $4 $8 $6

elif [ "$1" == "$uvar_fastx" ];
then
    python3 ../bin/fastx_findorfs.py $1 $2 $3 $4 $5 $6 $7 $8 $9 $10

else
    echo "Not found"
fi

#for arg in "$@"
#do
#    echo $arg
#done



